### ISSUE TITLE
【info】dugite : dugite-native构建的git的git绑定

### ISSUE THREAD

**Issue by Akimotorakiyu** [justjavac/deno_git#1]
为 github desktop 的 git 绑定
https://github.com/desktop/dugite

为 dugite 绑定专门构建 git
https://github.com/desktop/dugite-native

**Comment by justjavac** [comment]
有 2 个 rust 的：

- https://crates.io/crates/libgit2-sys
- https://crates.io/crates/git2

**Comment by justjavac** [comment]
dugite 是使用 nodejs 直接执行的系统 git 命令。

而 dugite-native 则是将 c++ 和 nodejs 做了绑定。

**Comment by Akimotorakiyu** [comment]
> 而 dugite-native 则是将 c++ 和 nodejs 做了绑定

@justjavac 好像没有绑定到node，应该只是打包生成了一个绿色版的git
