### ISSUE TITLE
Is there an ETA on completion? A roadmap?

### ISSUE THREAD

**Issue by ffMathy** [justjavac/deno_git#2]
When can we expect this to be done? Is it dead?

**Comment by somebody1234** [comment]
._.

**Comment by justjavac** [comment]
waiting for https://github.com/denoffi/denoffi

**Comment by KaKi87** [comment]
Hello,

> waiting for denoffi/denoffi

What are you waiting for regarding that repo ? An issue ? A PR ?

Thanks
